### ISSUE TITLE
Issues with downloaded tgz

### ISSUE THREAD

**Issue by hgheady** [ChaseLewis/cribl-example-app#1]
Hi Chase, thanks for your work on this project!

In testing I have uploaded and downloaded a tgz, and after download the MacOS default Archive Utility is not able to extract:
![image](https://user-images.githubusercontent.com/75589169/123137127-84563080-d408-11eb-9c30-10fda2652703.png)

Above is an issue that should be addressed. As more of an FYI, the same archive is extracted successfully on the command line, but tar does complain:
```
%> tar -xvf test0602\(1\).tgz
x tar_test/
x tar_test/foo.txt
x tar_test/Firefox 87.0.dmg
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
```

Fixing this would be a nice-to-have.

**Comment by ChaseLewis** [comment]
@hgheady This has been fixed. My naming scheme for the parts sometimes got them out of order since I didn't pad the chunk number. It should now work with 5*1024*1024*10^15 size files which most disks would fail with. My test file was too small to trigger this bug.
